add show job log in install smpe scripts
Signed-off-by: Jack (T.) Jia <jack-tiefeng.jia@ibm.com>

diff --git a/playbooks/roles/ptf/templates/install-SMPE-SYSMOD.sh.j2 b/playbooks/roles/ptf/templates/install-SMPE-SYSMOD.sh.j2
--- a/playbooks/roles/ptf/templates/install-SMPE-SYSMOD.sh.j2
+++ b/playbooks/roles/ptf/templates/install-SMPE-SYSMOD.sh.j2
@@ -146,6 +146,14 @@ then
     exit 9
 fi
 
+head -1 $operdir/show_job_log.rexx | grep REXX 1> /dev/null 2> /dev/null
+if [[ $? -ne 0 ]]
+then
+    echo $SCRIPT ERROR: show_job_log.rexx not found in $operdir or is not valid REXX 
+    echo $SCRIPT INFO: CWD is `pwd`
+    exit 9
+fi
+
 function runJob {
 
     echo; echo $SCRIPT function runJob started
@@ -220,6 +228,11 @@ function runJob {
         : # echo; echo $SCRIPT job JOB$jobid completed
     fi
 
+    # show job log for debugging purpose
+    echo $SCRIPT ====================== content start ======================
+    show_job_log.rexx "jobid=JOB${jobid} owner=* jobname=*"
+    echo $SCRIPT ====================== content end ========================
+
     # jobname=`sed -n 's/.*JOB(\([^ ]*\)).*/\1/p' $CIZT_TMP/dj.$$.cc`
     # echo $SCRIPT jobname $jobname
     
@@ -230,7 +243,7 @@ function runJob {
         echo $SCRIPT ERROR: no return code for jobid $jobid PID=$$
         echo $SCRIPT DISPLAY JOB output was:
         cat $CIZT_TMP/dj.$$.cc
-        # do NOT ... return 3
+        return 3
     fi
     
     rc=`sed -n 's/.*RC=\([0-9]*\))/\1/p' $CIZT_TMP/dj.$$.cc`
@@ -239,7 +252,7 @@ function runJob {
     if [[ $rc -gt 4 ]]
     then
         echo $SCRIPT ERROR: job "$jobname(JOB$jobid)" failed, RC=$rc 
-        # do NOT ... return 4
+        return 4
     else
         echo $SCRIPT INFO: job "$jobname(JOB$jobid)" ended, RC=$rc
     fi
@@ -333,7 +346,9 @@ do
         # hlq was just $hlq before ... s/#hlq/${hlq}/; \
 
     runJob $CIZT_TMP/$smpejob.sed.jcl
-    if [[ $? -ne 0 ]]
+    # Z2ACCEPT step is ok to fail because we did it when install FMID
+    # otherwise any job failure should exit and stop the following steps
+    if [[ $? -ne 0 && $smpejob != Z2ACCEPT ]]
     then
         echo $SCRIPT ERROR: SMP/E JOB $smpejob failed
         exit 2
@@ -347,8 +362,16 @@ do
         wrap_call tsocmd listds "'${hlq}.ZOWE.${FMID}.$SYSMOD2'" history status members
         echo "uss sysmod 1: $(ls -al $download_path/ZOWE.$FMID.$SYSMOD1)"
         echo "uss sysmod 2: $(ls -al $download_path/ZOWE.$FMID.$SYSMOD2)"
-        wrap_call cp $download_path/ZOWE.$FMID.$SYSMOD1 "//'${hlq}.ZOWE.${FMID}.$SYSMOD1'"
-        wrap_call cp $download_path/ZOWE.$FMID.$SYSMOD2 "//'${hlq}.ZOWE.${FMID}.$SYSMOD2'"
+        cp $download_path/ZOWE.$FMID.$SYSMOD1 "//'${hlq}.ZOWE.${FMID}.$SYSMOD1'"
+        if [[ $? -ne 0 ]]; then
+          echo $SCRIPT ERROR: copy $SYSMOD1 failed
+          exit 3
+        fi
+        cp $download_path/ZOWE.$FMID.$SYSMOD2 "//'${hlq}.ZOWE.${FMID}.$SYSMOD2'"
+        if [[ $? -ne 0 ]]; then
+          echo $SCRIPT ERROR: copy $SYSMOD2 failed
+          exit 3
+        fi
         echo "After sysmod copy:"
         wrap_call tsocmd listds "'${hlq}.ZOWE.${FMID}.$SYSMOD1'" history status members
         wrap_call tsocmd listds "'${hlq}.ZOWE.${FMID}.$SYSMOD2'" history status members
