Sync up pipeline changes from staging to master
Signed-off-by: Tom Zhang <t.yczhang@ibm.com>

diff --git a/.github/workflows/build-packaging.yml b/.github/workflows/build-packaging.yml
--- a/.github/workflows/build-packaging.yml
+++ b/.github/workflows/build-packaging.yml
@@ -5,80 +5,52 @@ on:
       - staging 
   pull_request:
     types: [opened, synchronize]
-  workflow_call:
-    inputs:
-      BUILD_SMPE:
-        required: false
-        type: boolean
-      BUILD_PSIANDSMPE:
-        required: false
-        type: boolean
-      BUILD_DOCKER:
-        required: false
-        type: boolean
-      BUILD_DOCKER_SOURCES:
-        required: false
-        type: boolean
-      BUILD_KUBERNETES:
-        required: false
-        type: boolean
-      KEEP_TEMP_PAX_FOLDER:
-        required: false
-        type: boolean
-    secrets:
-      JF_ARTIFACTORY_TOKEN:
-        required: true
-      SSH_MARIST_USERNAME:
-        required: true
-      SSH_MARIST_RACF_PASSWORD:
-        required: true
-      ZLINUX_SSH_KEY:
-        required: true
-      ZLINUX_HOST:
-        required: true
-      ZLINUX_SSH_USER:
-        required: true
-      ZLINUX_SSH_PASSPHRASE:
-        required: true
-      DOCKERHUB_USER:
-        required: true
-      DOCKERHUB_PASSWORD:
-        required: true
 
   workflow_dispatch:
     inputs:
       BUILD_SMPE:
         description: 'Build SMPE'
         required: false
-        default: 'false'
+        default: false
         type: boolean
-      BUILD_PSIANDSMPE:
-        description: 'Build PSI and SMPE'
+      BUILD_PSWI_SMPE:
+        description: 'Build PSWI and SMPE'
         required: false
-        default: 'false'
+        default: false
         type: boolean
       BUILD_DOCKER:
         description: 'Build Docker'
         required: false
-        default: 'false'
+        default: false
         type: boolean
       BUILD_DOCKER_SOURCES:
         description: 'Build Docker sources'
         required: false
-        default: 'false'
+        default: false
         type: boolean
       BUILD_KUBERNETES:
         description: 'Build Kubernetes'
         required: false
-        default: 'false'
+        default: false
         type: boolean
       KEEP_TEMP_PAX_FOLDER:
         description: 'do we need to keep temp pax folder?'
         required: false
-        default: 'false'
+        default: false
         type: boolean
+      RANDOM_DISPATCH_EVENT_ID:
+        description: 'random dispatch event id'
+        required: false
+        type: string
 
 jobs:
+  display-dispatch-event-id:
+    if: github.event.inputs.RANDOM_DISPATCH_EVENT_ID != ''
+    runs-on: ubuntu-latest
+    steps:
+      - name: RANDOM_DISPATCH_EVENT_ID is ${{ github.event.inputs.RANDOM_DISPATCH_EVENT_ID }}
+        run: echo "prints random dispatch event id sent from workflow dispatch event"
+
   check-permission:
     runs-on: ubuntu-latest
     steps:
@@ -105,16 +77,18 @@ jobs:
           COMMIT_HASH=$(git rev-parse --verify HEAD)
           CURRENT_TIME=$(date +%s)
           if [[ -z "${{ github.event.pull_request.number }}" ]]; then
-            # meaning the workflow is triggered from pull_request 
-            # now try to find out if a PR is opened against this running branch
+            # meaning the workflow is NOT triggered from pull_request 
+            # sometimes user can manually trigger a workflow on a branch that a PR is open,
+            # thus try to find out if a PR is opened against this running branch
             pr_num=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref }} | jq -r '.[] | .number')
             if [[ -z "$pr_num" ]]; then
-              echo CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
+              # meaning PR is not open, we collect the branch name
+              CURRENT_BRANCH=${GITHUB_REF_NAME}
             else
-              echo CURRENT_BRANCH=PR-$pr_num
+              CURRENT_BRANCH=PR-$pr_num
             fi
           else
-            echo CURRENT_BRANCH=PR-${{ github.event.pull_request.number }}
+            CURRENT_BRANCH=PR-${{ github.event.pull_request.number }}
           fi
 
           sed -e "s#{BUILD_BRANCH}#${CURRENT_BRANCH}#g" \
@@ -141,61 +115,38 @@ jobs:
               console.error('Cannot read manifest or manifest is invalid.');
             }
 
-      - name: '[Prep 6] Process github.event.inputs and inputs'
+      - name: '[Prep 6] Process github.event.inputs'
         id: process-inputs
         run: |
           BUILD_WHAT="PAX"
-          if [[ -z "${{ github.event.inputs.BUILD_SMPE }}" ]]; then
-            echo INPUTS_BUILD_SMPE=${{ inputs.BUILD_SMPE }} >> $GITHUB_ENV
-          else 
-            echo INPUTS_BUILD_SMPE=${{ github.event.inputs.BUILD_SMPE }} >> $GITHUB_ENV
-            if [[ "${{ github.event.inputs.BUILD_SMPE }}" == true ]]; then
-              BUILD_WHAT=$BUILD_WHAT", SMPE"
-            fi
+          
+          echo INPUTS_BUILD_SMPE=${{ github.event.inputs.BUILD_SMPE }} >> $GITHUB_ENV
+          if [[ "${{ github.event.inputs.BUILD_SMPE }}" == true ]]; then
+            BUILD_WHAT=$BUILD_WHAT", SMPE"
           fi
           
-          if [[ -z "${{ github.event.inputs.BUILD_PSIANDSMPE }}" ]]; then
-            echo INPUTS_BUILD_PSIANDSMPE=${{ inputs.BUILD_PSIANDSMPE }} >> $GITHUB_ENV
-          else 
-            echo INPUTS_BUILD_PSIANDSMPE=${{ github.event.inputs.BUILD_PSIANDSMPE }} >> $GITHUB_ENV
-            if [[ "${{ github.event.inputs.BUILD_PSIANDSMPE }}" == true ]]; then
-              BUILD_WHAT=$BUILD_WHAT", PSIANDSMPE"
-            fi
+          echo INPUTS_BUILD_PSWI_SMPE=${{ github.event.inputs.BUILD_PSWI_SMPE }} >> $GITHUB_ENV
+          if [[ "${{ github.event.inputs.BUILD_PSWI_SMPE }}" == true ]]; then
+            BUILD_WHAT=$BUILD_WHAT", PSWI+SMPE"
+          fi
+                  
+          echo INPUTS_BUILD_DOCKER=${{ github.event.inputs.BUILD_DOCKER }} >> $GITHUB_ENV
+          if [[ "${{ github.event.inputs.BUILD_DOCKER }}" == true ]]; then
+            BUILD_WHAT=$BUILD_WHAT", DOCKER"
+          fi
+                
+          echo INPUTS_BUILD_DOCKER_SOURCES=${{ github.event.inputs.BUILD_DOCKER_SOURCES }} >> $GITHUB_ENV
+          if [[ "${{ github.event.inputs.BUILD_DOCKER_SOURCES }}" == true ]]; then
+            BUILD_WHAT=$BUILD_WHAT", DOCKER_SOURCES"
+          fi   
+
+          echo INPUTS_BUILD_KUBERNETES=${{ github.event.inputs.BUILD_KUBERNETES }} >> $GITHUB_ENV
+          if [[ "${{ github.event.inputs.BUILD_KUBERNETES }}" == true ]]; then
+            BUILD_WHAT=$BUILD_WHAT", K8S"
           fi
 
-          if [[ -z "${{ github.event.inputs.BUILD_DOCKER }}" ]]; then
-            echo INPUTS_BUILD_DOCKER=${{ inputs.BUILD_DOCKER }} >> $GITHUB_ENV
-          else 
-            echo INPUTS_BUILD_DOCKER=${{ github.event.inputs.BUILD_DOCKER }} >> $GITHUB_ENV
-            if [[ "${{ github.event.inputs.BUILD_DOCKER }}" == true ]]; then
-              BUILD_WHAT=$BUILD_WHAT", DOCKER"
-            fi
-          fi
-
-          if [[ -z "${{ github.event.inputs.BUILD_DOCKER_SOURCES }}" ]]; then
-            echo INPUTS_BUILD_DOCKER_SOURCES=${{ inputs.BUILD_DOCKER_SOURCES }} >> $GITHUB_ENV
-          else 
-            echo INPUTS_BUILD_DOCKER_SOURCES=${{ github.event.inputs.BUILD_DOCKER_SOURCES }} >> $GITHUB_ENV
-            if [[ "${{ github.event.inputs.BUILD_DOCKER_SOURCES }}" == true ]]; then
-              BUILD_WHAT=$BUILD_WHAT", DOCKER_SOURCES"
-            fi
-          fi
-
-          if [[ -z "${{ github.event.inputs.BUILD_KUBERNETES }}" ]]; then
-            echo INPUTS_BUILD_KUBERNETES=${{ inputs.BUILD_KUBERNETES }} >> $GITHUB_ENV
-          else 
-            echo INPUTS_BUILD_KUBERNETES=${{ github.event.inputs.BUILD_KUBERNETES }} >> $GITHUB_ENV
-            if [[ "${{ github.event.inputs.BUILD_KUBERNETES }}" == true ]]; then
-              BUILD_WHAT=$BUILD_WHAT", K8S"
-            fi
-          fi
-
-          if [[ -z "${{ github.event.inputs.KEEP_TEMP_PAX_FOLDER }}" ]]; then
-            echo INPUTS_KEEP_TEMP_PAX_FOLDER=${{ inputs.KEEP_TEMP_PAX_FOLDER }} >> $GITHUB_ENV
-          else 
-            echo INPUTS_KEEP_TEMP_PAX_FOLDER=${{ github.event.inputs.KEEP_TEMP_PAX_FOLDER }} >> $GITHUB_ENV
-          fi
-
+          echo INPUTS_KEEP_TEMP_PAX_FOLDER=${{ github.event.inputs.KEEP_TEMP_PAX_FOLDER }} >> $GITHUB_ENV
+          
           echo ::set-output name=BUILD_WHAT::$BUILD_WHAT
       
       - name: '[Prep 7] Comment on PR to indicate build is started'
@@ -246,17 +197,19 @@ jobs:
           manifest-file-path: ${{ github.workspace }}/manifest.json
           default-target-path: .pax/content/zowe-${{ env.P_VERSION }}/files/
           expected-count: 30
+        # env:
+        #   DEBUG: 'zowe-actions:shared-actions:jfrog-download'
       
       # this step is not doing a publish, we are just utilizing this actions to get the PUBLISH_TARGET_PATH, 
       # and it will be used in the next step: [Download 3] Download SMPE build log
       - name: '[SMPE Download 2] Get publish target path'
         timeout-minutes: 5
-        if: env.INPUTS_BUILD_SMPE == 'true' || env.INPUTS_BUILD_PSIANDSMPE == 'true'
+        if: env.INPUTS_BUILD_SMPE == 'true' || env.INPUTS_BUILD_PSWI_SMPE == 'true'
         uses: zowe-actions/shared-actions/publish@main
 
       - name: '[SMPE Download 3] Download SMPE build log'
         timeout-minutes: 5
-        if: env.INPUTS_BUILD_SMPE == 'true' || env.INPUTS_BUILD_PSIANDSMPE == 'true'
+        if: env.INPUTS_BUILD_SMPE == 'true' || env.INPUTS_BUILD_PSWI_SMPE == 'true'
         uses: zowe-actions/shared-actions/jfrog-download@main
         with:
           source-path-or-pattern: ${{ env.PUBLISH_TARGET_PATH }}smpe-build-logs-*.pax.Z
@@ -267,7 +220,7 @@ jobs:
       - name: '[PAX/SMPE 1] Pre-packaging'
         id: pax-prep
         run: |
-          if [ "${{ env.INPUTS_BUILD_SMPE }}" == "true" ] || [ "${{ env.INPUTS_BUILD_PSIANDSMPE }}" == "true" ] ; then
+          if [ "${{ env.INPUTS_BUILD_SMPE }}" == "true" ] || [ "${{ env.INPUTS_BUILD_PSWI_SMPE }}" == "true" ] ; then
             echo ::set-output name=EXTRA_FILES::zowe-smpe.zip,fmid.zip,pd.htm,smpe-promote.tar,smpe-build-logs.pax.Z,rename-back.sh
             echo ::set-output name=BUILD_SMPE::yes
           else
@@ -275,11 +228,6 @@ jobs:
             echo ::set-output name=BUILD_SMPE::
           fi
           
-          if [ "${{ env.INPUTS_BUILD_PSIANDSMPE }}" == "true" ] ; then
-            echo ::set-output name=BUILD_PSI::yes
-          else
-            echo ::set-output name=BUILD_PSI::
-          fi
           if [ "${{ env.INPUTS_KEEP_TEMP_PAX_FOLDER }}" == "true" ] ; then
             echo ::set-output name=KEEP_TEMP_FOLDER::yes
           else
@@ -299,29 +247,36 @@ jobs:
           extra-environment-vars: |
             ZOWE_VERSION=${{ env.P_VERSION }}
             BUILD_SMPE=${{ steps.pax-prep.outputs.BUILD_SMPE }}
-            BUILD_PSI=${{ steps.pax-prep.outputs.BUILD_PSI }}
             KEEP_TEMP_FOLDER=${{ steps.pax-prep.outputs.KEEP_TEMP_FOLDER }}
 
       - name: '[SMPE Pax 3] Post-make pax'
-        if: env.INPUTS_BUILD_SMPE == 'true' || env.INPUTS_BUILD_PSIANDSMPE == 'true'
+        if: env.INPUTS_BUILD_SMPE == 'true' || env.INPUTS_BUILD_PSWI_SMPE == 'true'
         run: |
           cd .pax
           chmod +x rename-back.sh
           cat rename-back.sh
           ./rename-back.sh
 
-      - name: '[PAX/SMPE Publish] Upload to artifactory'
-        id: publish
-        timeout-minutes: 5
-        uses: zowe-actions/shared-actions/publish@main
+      - name: '[PSI-LOCK] Lock marist servers to build PSWI'
+        uses: zowe-actions/shared-actions/lock-resource@main
+        if: env.INPUTS_BUILD_PSWI_SMPE == 'true'
         with:
-          artifacts: |
-            .pax/zowe.pax
-            .pax/zowe-smpe.zip
-            .pax/smpe-promote.tar
-            .pax/pd.htm
-            .pax/smpe-build-logs.pax.Z
-            .pax/AZWE*
+          lock-repository: ${{ github.repository }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          lock-resource-name: zowe-psi-build-zzow03-lock
+          lock-avg-retry-interval: 60
+      
+      - name: '[SMPE Pax 4] Build PSWI'
+        if: env.INPUTS_BUILD_PSWI_SMPE == 'true'
+        timeout-minutes: 60
+        run: |
+          cd pswi
+          chmod +x PSWI-marist.sh 
+          ./PSWI-marist.sh
+        env:
+          ZOSMF_USER: ${{ secrets.ZOWE_PSWI_BUILD_USR }}
+          ZOSMF_PASS: ${{ secrets.ZOWE_PSWI_BUILD_PASSWD }}
+          VERSION: ${{ env.P_VERSION }}
 
       - name: '[TP_ZLINUX_DOCKER 1] Configure SSH'
         if: env.INPUTS_BUILD_DOCKER == 'true'
@@ -345,36 +300,22 @@ jobs:
         uses: zowe-actions/shared-actions/tech-preview-build-zlinux-docker@main
         with: 
           run-number: ${{ github.run_number }}
-          zowe-pax-jfrog-upload-target: ${{ steps.publish.outputs.zowe-pax-jfrog-upload-target }}
           build-docker-sources: ${{ env.INPUTS_BUILD_DOCKER_SOURCES }}
           dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
           dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
           zlinux-ssh-server: zlinux
           zlinux-ssh-key-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
 
-      - name: '[TP_ZLINUX_DOCKER 3] Upload zlinux docker to artifactory'
+      - name: '[TP_LINUX_DOCKER 1] Copy zowe.pax to prepare for building Linux Docker'
         timeout-minutes: 5
         if: env.INPUTS_BUILD_DOCKER == 'true'
-        uses: zowe-actions/shared-actions/publish@main
-        with:
-          artifacts: server-bundle.s390x.tar
-
-      - name: '[TP_ZLINUX_DOCKER 4] Upload zlinux docker sources to artifactory'
-        timeout-minutes: 5
-        if: env.INPUTS_BUILD_DOCKER_SOURCES == 'true'
-        uses: zowe-actions/shared-actions/publish@main
-        with:
-          artifacts: server-bundle.sources.s390x.tar
-
-      - name: '[TP_LINUX_DOCKER 1] Download zowe.pax'
-        timeout-minutes: 5
-        if: env.INPUTS_BUILD_DOCKER == 'true'
-        uses: zowe-actions/shared-actions/jfrog-download@main
-        with:
-          source-path-or-pattern: ${{ steps.publish.outputs.zowe-pax-jfrog-upload-target }}
-          default-target-path: 'containers/server-bundle/zowe.pax'
-          extra-options: --flat=true
-          expected-count: 1
+        run: |
+          if [[ -f ".pax/zowe.pax" ]]; then
+            cp ".pax/zowe.pax" "containers/server-bundle/zowe.pax"
+          else
+            echo ".pax/zowe.pax not found, error building Linux Docker"
+            exit 1
+          fi
       
       - name: '[TP_LINUX_DOCKER 2] Build Linux Docker'
         if: env.INPUTS_BUILD_DOCKER == 'true'
@@ -401,22 +342,8 @@ jobs:
           # show files
           echo ">>>>>>>>>>>>>>>>>> docker tar: "
           pwd && ls -ltr server-bundle.*
-          
-      - name: '[TP_LINUX_DOCKER 3] Upload linux docker to artifactory'
-        timeout-minutes: 5
-        if: env.INPUTS_BUILD_DOCKER == 'true'
-        uses: zowe-actions/shared-actions/publish@main
-        with:
-          artifacts: containers/server-bundle/server-bundle.amd64.tar
 
-      - name: '[TP_LINUX_DOCKER 4] Upload linux docker sources to artifactory'
-        timeout-minutes: 5
-        if: env.INPUTS_BUILD_DOCKER_SOURCES == 'true'
-        uses: zowe-actions/shared-actions/publish@main
-        with:
-          artifacts: containers/server-bundle/server-bundle.sources.amd64.tar
-
-      - name: '[K8S 1] Build Kubernetes'
+      - name: '[K8S] Build Kubernetes'
         timeout-minutes: 10
         if: env.INPUTS_BUILD_KUBERNETES == 'true'
         working-directory: containers
@@ -424,12 +351,23 @@ jobs:
           ./build/parse-manifest-to-deployment.sh
           zip -r zowe-containerization.zip kubernetes
 
-      - name: '[K8S 2] Upload k8s zip to artifactory'
-        timeout-minutes: 5
-        if: env.INPUTS_BUILD_KUBERNETES == 'true'
+      - name: 'Upload everything to artifactory'
+        timeout-minutes: 10
         uses: zowe-actions/shared-actions/publish@main
         with:
-          artifacts: containers/zowe-containerization.zip
+          artifacts: |
+            .pax/zowe.pax
+            .pax/zowe-smpe.zip
+            .pax/smpe-promote.tar
+            .pax/pd.htm
+            .pax/smpe-build-logs.pax.Z
+            .pax/AZWE*
+            .pax/zowe-PSWI*
+            server-bundle.s390x.tar
+            server-bundle.sources.s390x.tar
+            containers/server-bundle/server-bundle.amd64.tar
+            containers/server-bundle/server-bundle.sources.amd64.tar
+            containers/zowe-containerization.zip
 
       - name: '[Post Prep 7] Update PR comment to indicate build succeeded'
         uses: actions/github-script@v5
@@ -471,20 +409,37 @@ jobs:
             });
 
   # only run auto integration tests when the workflow is triggered by pull request
+  # default running Convenience Pax on any zzow server
   call-integration-test:
     needs: regular-build
+    runs-on: ubuntu-latest
     if: github.event_name == 'pull_request' || (github.event_name == 'push' && contains(github.ref, 'staging'))
-    uses: zowe/zowe-install-packaging/.github/workflows/cicd-test.yml@staging
-    with: 
-      pr-auto-test: true
-      pr-auto-build-num: ${{ github.run_number }}
-    secrets:
-      JF_ARTIFACTORY_TOKEN: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
-      SSH_HOST: ${{ secrets.SSH_HOST }}
-      SSH_PORT: ${{ secrets.SSH_PORT }}
-      SSH_USER: ${{ secrets.SSH_USER }}
-      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
-    # Above secrets exists in the environment, doing secrets here to mitigate a problem of
-    #   reusable workflows where environment secret can not be passed in properly
-    # More info: https://github.community/t/reusable-workflows-secrets-and-environments/203695/23
-    # it was a bit weird to pass in above secrets, hope Github team can improve/fix on this
+    steps:
+      - name: 'Determine branch name'
+        run: |
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
+          else
+            echo "BRANCH_NAME=$(echo ${GITHUB_REF_NAME})" >> $GITHUB_ENV
+          fi
+
+      - name: 'Call test workflow'
+        uses: zowe-actions/shared-actions/workflow-remote-call-wait@main
+        id: call-test
+        with:
+          github-token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
+          owner: zowe
+          repo: zowe-install-packaging
+          workflow-filename: cicd-test.yml
+          branch-name: ${{ env.BRANCH_NAME }}
+          poll-frequency: 3
+          inputs-json-string: '{"custom-zowe-artifactory-pattern-or-build-number":"${{ github.run_number }}"}'
+        # env:
+        #   DEBUG: 'workflow-remote-call-wait'
+      
+      - name: 'Report test failure if applied'
+        if: ${{ steps.call-test.outputs.workflow-run-conclusion != 'success' }}
+        uses: actions/github-script@v5
+        with:
+          script: |
+            core.setFailed('Test workflow ${{ steps.call-test.outputs.workflow-run-num }} is not successful')
