Merge multiple upload steps into a single one
Signed-off-by: Tom Zhang <t.yczhang@ibm.com>

diff --git a/.github/workflows/build-packaging.yml b/.github/workflows/build-packaging.yml
--- a/.github/workflows/build-packaging.yml
+++ b/.github/workflows/build-packaging.yml
@@ -278,20 +278,6 @@ jobs:
           ZOSMF_PASS: ${{ secrets.ZOWE_PSWI_BUILD_PASSWD }}
           VERSION: ${{ env.P_VERSION }}
 
-      - name: '[PAX/SMPE Publish] Upload to artifactory'
-        id: publish
-        timeout-minutes: 5
-        uses: zowe-actions/shared-actions/publish@main
-        with:
-          artifacts: |
-            .pax/zowe.pax
-            .pax/zowe-smpe.zip
-            .pax/smpe-promote.tar
-            .pax/pd.htm
-            .pax/smpe-build-logs.pax.Z
-            .pax/AZWE*
-            .pax/zowe-PSWI*
-
       - name: '[TP_ZLINUX_DOCKER 1] Configure SSH'
         if: env.INPUTS_BUILD_DOCKER == 'true'
         run: |
@@ -314,36 +300,22 @@ jobs:
         uses: zowe-actions/shared-actions/tech-preview-build-zlinux-docker@main
         with: 
           run-number: ${{ github.run_number }}
-          zowe-pax-jfrog-upload-target: ${{ steps.publish.outputs.zowe-pax-jfrog-upload-target }}
           build-docker-sources: ${{ env.INPUTS_BUILD_DOCKER_SOURCES }}
           dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
           dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
           zlinux-ssh-server: zlinux
           zlinux-ssh-key-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
 
-      - name: '[TP_ZLINUX_DOCKER 3] Upload zlinux docker to artifactory'
+      - name: '[TP_LINUX_DOCKER 1] Copy zowe.pax to prepare for building Linux Docker'
         timeout-minutes: 5
         if: env.INPUTS_BUILD_DOCKER == 'true'
-        uses: zowe-actions/shared-actions/publish@main
-        with:
-          artifacts: server-bundle.s390x.tar
-
-      - name: '[TP_ZLINUX_DOCKER 4] Upload zlinux docker sources to artifactory'
-        timeout-minutes: 5
-        if: env.INPUTS_BUILD_DOCKER_SOURCES == 'true'
-        uses: zowe-actions/shared-actions/publish@main
-        with:
-          artifacts: server-bundle.sources.s390x.tar
-
-      - name: '[TP_LINUX_DOCKER 1] Download zowe.pax'
-        timeout-minutes: 5
-        if: env.INPUTS_BUILD_DOCKER == 'true'
-        uses: zowe-actions/shared-actions/jfrog-download@main
-        with:
-          source-path-or-pattern: ${{ steps.publish.outputs.zowe-pax-jfrog-upload-target }}
-          default-target-path: 'containers/server-bundle/zowe.pax'
-          extra-options: --flat=true
-          expected-count: 1
+        run: |
+          if [[ -f ".pax/zowe.pax" ]]; then
+            cp ".pax/zowe.pax" "containers/server-bundle/zowe.pax"
+          else
+            echo ".pax/zowe.pax not found, error building Linux Docker"
+            exit 1
+          fi
       
       - name: '[TP_LINUX_DOCKER 2] Build Linux Docker'
         if: env.INPUTS_BUILD_DOCKER == 'true'
@@ -370,22 +342,8 @@ jobs:
           # show files
           echo ">>>>>>>>>>>>>>>>>> docker tar: "
           pwd && ls -ltr server-bundle.*
-          
-      - name: '[TP_LINUX_DOCKER 3] Upload linux docker to artifactory'
-        timeout-minutes: 5
-        if: env.INPUTS_BUILD_DOCKER == 'true'
-        uses: zowe-actions/shared-actions/publish@main
-        with:
-          artifacts: containers/server-bundle/server-bundle.amd64.tar
 
-      - name: '[TP_LINUX_DOCKER 4] Upload linux docker sources to artifactory'
-        timeout-minutes: 5
-        if: env.INPUTS_BUILD_DOCKER_SOURCES == 'true'
-        uses: zowe-actions/shared-actions/publish@main
-        with:
-          artifacts: containers/server-bundle/server-bundle.sources.amd64.tar
-
-      - name: '[K8S 1] Build Kubernetes'
+      - name: '[K8S] Build Kubernetes'
         timeout-minutes: 10
         if: env.INPUTS_BUILD_KUBERNETES == 'true'
         working-directory: containers
@@ -393,12 +351,23 @@ jobs:
           ./build/parse-manifest-to-deployment.sh
           zip -r zowe-containerization.zip kubernetes
 
-      - name: '[K8S 2] Upload k8s zip to artifactory'
-        timeout-minutes: 5
-        if: env.INPUTS_BUILD_KUBERNETES == 'true'
+      - name: 'Upload everything to artifactory'
+        timeout-minutes: 10
         uses: zowe-actions/shared-actions/publish@main
         with:
-          artifacts: containers/zowe-containerization.zip
+          artifacts: |
+            .pax/zowe.pax
+            .pax/zowe-smpe.zip
+            .pax/smpe-promote.tar
+            .pax/pd.htm
+            .pax/smpe-build-logs.pax.Z
+            .pax/AZWE*
+            .pax/zowe-PSWI*
+            server-bundle.s390x.tar
+            server-bundle.sources.s390x.tar
+            containers/server-bundle/server-bundle.amd64.tar
+            containers/server-bundle/server-bundle.sources.amd64.tar
+            containers/zowe-containerization.zip
 
       - name: '[Post Prep 7] Update PR comment to indicate build succeeded'
         uses: actions/github-script@v5
