comment out keep curl in cicd test
Signed-off-by: Tom Zhang <14881754+FlappiTomic@users.noreply.github.com>

diff --git a/.github/workflows/cicd-test.yml b/.github/workflows/cicd-test.yml
--- a/.github/workflows/cicd-test.yml
+++ b/.github/workflows/cicd-test.yml
@@ -454,20 +454,20 @@ jobs:
               body: body
             });
 
-  keep-curl:
-    runs-on: ubuntu-latest
-    needs: make-matrix
-    strategy:
-      matrix: ${{ fromJson(needs.make-matrix.outputs.matrix) }}
-      fail-fast: false
-    environment: ${{ matrix.server }}
-    steps:
-      - name: curl gateway
-        timeout-minutes: 180
-        run: |
-          sleep 30m
+  # keep-curl:
+  #   runs-on: ubuntu-latest
+  #   needs: make-matrix
+  #   strategy:
+  #     matrix: ${{ fromJson(needs.make-matrix.outputs.matrix) }}
+  #     fail-fast: false
+  #   environment: ${{ matrix.server }}
+  #   steps:
+  #     - name: curl gateway
+  #       timeout-minutes: 180
+  #       run: |
+  #         sleep 30m
 
-          while sleep 5;
-          do
-            curl -k -s -S https://${{ secrets.SSH_HOST }}:7554 1>/dev/null || true;
-          done
+  #         while sleep 5;
+  #         do
+  #           curl -k -s -S https://${{ secrets.SSH_HOST }}:7554 1>/dev/null || true;
+  #         done
